### ISSUE TITLE
Reliability/durability?

### ISSUE THREAD

**Issue by maiorfi** [dukov777/esp8266-evb-lua#1]
Hi. How long did you manage to get this lua app running without rebooting?

**Comment by dukov777** [comment]
Hi, 
I let it work for several hours with almost no load (these are my work conditions).

Your question triggers the QA in me and I will write a test.

The basic test scenario:
1: Test is publish a message to esp.
2: esp8266 loops the message back to test.
3: Test: waits esp to reply and logs the result. If test encounters a receive timeout (no idea how long is OK, maybe ~1 min) the test is considered FAIL.

Let you know for the results.

**Comment by dukov777** [comment]
The code was put under test for about 14 hours without any errors.
The test cases are in [testing](https://github.com/dukov777/esp8266-evb-lua/tree/testing) branch.
